// This file is auto-generated by vite-plugin-openapi-codegen.
// Do not edit manually. Changes will be overwritten on next build.

import type {
  CatalogItemPath,
  CatalogItemsQuery,
  ExampleItemPath,
  ExampleSearchQuery,
  FulfillmentOrderPath,
  IdentityUserPath,
  OrderPath,
} from './types'

function buildQuery(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v != null)
  if (entries.length === 0) return ''
  return '?' + entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')
}

// Auth
export function postAuthLogin(): string {
  return 'auth/login'
}
export function postAuthLogout(): string {
  return 'auth/logout'
}
export function getAuthMe(): string {
  return 'auth/me'
}
export function postAuthRefresh(): string {
  return 'auth/refresh'
}

// Catalog
export function getCatalogCategories(): string {
  return 'catalog/categories'
}
export function getCatalogItems(params: CatalogItemsQuery): string {
  return 'catalog/items' + buildQuery(params)
}
export function getCatalogItem(params: CatalogItemPath): string {
  return `catalog/items/${params.item_id}`
}
export function getCatalogStore(): string {
  return 'catalog/store'
}

// Examples
export function postExamplesEcho(): string {
  return 'examples/echo'
}
export function getExamplesItem(params: ExampleItemPath): string {
  return `examples/items/${params.item_id}`
}
export function getExamplesSearch(params: ExampleSearchQuery): string {
  return 'examples/search' + buildQuery(params)
}

// Identity
export function postIdentityUsers(): string {
  return 'identity/users'
}
export function getIdentityUser(params: IdentityUserPath): string {
  return `identity/users/${params.user_id}`
}
export function postIdentityUserDisable(params: IdentityUserPath): string {
  return `identity/users/${params.user_id}/disable`
}
export function postIdentityUserIdentities(params: IdentityUserPath): string {
  return `identity/users/${params.user_id}/identities`
}
export function patchIdentityUserProfile(params: IdentityUserPath): string {
  return `identity/users/${params.user_id}/profile`
}
export function postIdentityUserSoftDelete(params: IdentityUserPath): string {
  return `identity/users/${params.user_id}/soft-delete`
}

// Orders
export function getOrders(): string {
  return 'orders'
}
export function postOrders(): string {
  return 'orders'
}
export function getOrder(params: OrderPath): string {
  return `orders/${params.order_id}`
}
export function postOrderAccept(params: FulfillmentOrderPath): string {
  return `orders/${params.order_id}/accept`
}
export function postOrderCancel(params: OrderPath): string {
  return `orders/${params.order_id}/cancel`
}
export function postOrderComplete(params: FulfillmentOrderPath): string {
  return `orders/${params.order_id}/complete`
}
export function postOrderReady(params: FulfillmentOrderPath): string {
  return `orders/${params.order_id}/ready`
}
export function postOrderReject(params: FulfillmentOrderPath): string {
  return `orders/${params.order_id}/reject`
}
export function postOrderStartPreparing(params: FulfillmentOrderPath): string {
  return `orders/${params.order_id}/start-preparing`
}
