// This file is auto-generated by vite-plugin-openapi-codegen.
// Do not edit manually. Changes will be overwritten on next build.

import type { operations } from './api-types'

// Auth
export function postAuthLogin(): string {
  return 'auth/login'
}
export function postAuthLogout(): string {
  return 'auth/logout'
}
export function getAuthMe(): string {
  return 'auth/me'
}
export function postAuthRefresh(): string {
  return 'auth/refresh'
}

// Catalog
export function getCatalogCategories(): string {
  return 'catalog/categories'
}
export function getCatalogItems(): string {
  return 'catalog/items'
}
export function getCatalogItem(params: operations['get_item']['parameters']['path']): string {
  return `catalog/items/${params.item_id}`
}
export function getCatalogStore(): string {
  return 'catalog/store'
}

// Examples
export function postExamplesEcho(): string {
  return 'examples/echo'
}
export function getExamplesItem(
  params: operations['get_example_item']['parameters']['path'],
): string {
  return `examples/items/${params.item_id}`
}
export function getExamplesSearch(): string {
  return 'examples/search'
}

// Identity
export function postIdentityUsers(): string {
  return 'identity/users'
}
export function getIdentityUser(params: operations['get_user']['parameters']['path']): string {
  return `identity/users/${params.user_id}`
}
export function postIdentityUserDisable(
  params: operations['disable_user']['parameters']['path'],
): string {
  return `identity/users/${params.user_id}/disable`
}
export function postIdentityUserIdentities(
  params: operations['bind_user_identity']['parameters']['path'],
): string {
  return `identity/users/${params.user_id}/identities`
}
export function patchIdentityUserProfile(
  params: operations['update_user_profile']['parameters']['path'],
): string {
  return `identity/users/${params.user_id}/profile`
}
export function postIdentityUserSoftDelete(
  params: operations['soft_delete_user']['parameters']['path'],
): string {
  return `identity/users/${params.user_id}/soft-delete`
}

// Orders
export function getOrders(): string {
  return 'orders'
}
export function postOrders(): string {
  return 'orders'
}
export function getOrder(params: operations['get_order']['parameters']['path']): string {
  return `orders/${params.order_id}`
}
export function postOrderAccept(params: operations['accept_order']['parameters']['path']): string {
  return `orders/${params.order_id}/accept`
}
export function postOrderCancel(params: operations['cancel_order']['parameters']['path']): string {
  return `orders/${params.order_id}/cancel`
}
export function postOrderComplete(
  params: operations['complete_order']['parameters']['path'],
): string {
  return `orders/${params.order_id}/complete`
}
export function postOrderReady(
  params: operations['mark_order_ready']['parameters']['path'],
): string {
  return `orders/${params.order_id}/ready`
}
export function postOrderReject(params: operations['reject_order']['parameters']['path']): string {
  return `orders/${params.order_id}/reject`
}
export function postOrderStartPreparing(
  params: operations['start_preparing_order']['parameters']['path'],
): string {
  return `orders/${params.order_id}/start-preparing`
}
