// This file is auto-generated by vite-plugin-openapi-codegen.
// Do not edit manually. Changes will be overwritten on next build.

import type { ApiRequestOptions } from '#/integrations/http'
import { requestJson, requestVoid } from '#/integrations/http'
import type { operations } from './api-types'

import type {
  AuthMeResponse,
  AuthResponse,
  BindIdentityUserIdentityRequest,
  CatalogCategoriesResponse,
  CatalogItemResponse,
  CatalogItemsQuery,
  CatalogItemsResponse,
  CatalogStoreCatalogResponse,
  CreateIdentityUserRequest,
  ExampleItemResponse,
  ExamplePayload,
  ExamplePayloadResponse,
  ExampleSearchQuery,
  ExampleSearchResponse,
  FulfillmentOrderResponse,
  IdentityUserResponse,
  LoginRequest,
  OrderListResponse,
  OrderResponse,
  PlaceOrderRequest,
  UpdateIdentityUserProfileRequest,
} from './types'

import {
  postAuthLogin as buildPostAuthLoginPath,
  postAuthLogout as buildPostAuthLogoutPath,
  getAuthMe as buildGetAuthMePath,
  postAuthRefresh as buildPostAuthRefreshPath,
  getCatalogCategories as buildGetCatalogCategoriesPath,
  getCatalogItems as buildGetCatalogItemsPath,
  getCatalogItem as buildGetCatalogItemPath,
  getCatalogStore as buildGetCatalogStorePath,
  postExamplesEcho as buildPostExamplesEchoPath,
  getExamplesItem as buildGetExamplesItemPath,
  getExamplesSearch as buildGetExamplesSearchPath,
  postIdentityUsers as buildPostIdentityUsersPath,
  getIdentityUser as buildGetIdentityUserPath,
  postIdentityUserDisable as buildPostIdentityUserDisablePath,
  postIdentityUserIdentities as buildPostIdentityUserIdentitiesPath,
  patchIdentityUserProfile as buildPatchIdentityUserProfilePath,
  postIdentityUserSoftDelete as buildPostIdentityUserSoftDeletePath,
  getOrders as buildGetOrdersPath,
  postOrders as buildPostOrdersPath,
  getOrder as buildGetOrderPath,
  postOrderAccept as buildPostOrderAcceptPath,
  postOrderCancel as buildPostOrderCancelPath,
  postOrderComplete as buildPostOrderCompletePath,
  postOrderReady as buildPostOrderReadyPath,
  postOrderReject as buildPostOrderRejectPath,
  postOrderStartPreparing as buildPostOrderStartPreparingPath,
} from './api'

type RuntimeRequestOptions = Omit<ApiRequestOptions, 'json' | 'method' | 'searchParams' | 'signal'>

function buildSearchParams(query: Record<string, unknown>): URLSearchParams | undefined {
  const entries = Object.entries(query).filter(([, value]) => value != null)
  if (entries.length === 0) return undefined
  const searchParams = new URLSearchParams()
  for (const [key, value] of entries) {
    searchParams.set(key, String(value))
  }
  return searchParams
}

// Auth
export interface PostAuthLoginOptions {
  query?: never
  path?: never
  body: LoginRequest
  signal?: AbortSignal
}

export function postAuthLogin(
  options: PostAuthLoginOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<AuthResponse> {
  return requestJson<AuthResponse>(
    buildPostAuthLoginPath(),
    {
    ...requestOptions,
    method: 'POST',
    json: options.body,
    signal: options.signal,
    },
  )
}
export interface PostAuthLogoutOptions {
  query?: never
  path?: never
  body?: never
  signal?: AbortSignal
}

export function postAuthLogout(
  options: PostAuthLogoutOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<void> {
  return requestVoid(
    buildPostAuthLogoutPath(),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}
export interface GetAuthMeOptions {
  query?: never
  path?: never
  body?: never
  signal?: AbortSignal
}

export function getAuthMe(
  options: GetAuthMeOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<AuthMeResponse> {
  return requestJson<AuthMeResponse>(
    buildGetAuthMePath(),
    {
    ...requestOptions,
    method: 'GET',
    signal: options.signal,
    },
  )
}
export interface PostAuthRefreshOptions {
  query?: never
  path?: never
  body?: never
  signal?: AbortSignal
}

export function postAuthRefresh(
  options: PostAuthRefreshOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<AuthResponse> {
  return requestJson<AuthResponse>(
    buildPostAuthRefreshPath(),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}

// Catalog
export interface GetCatalogCategoriesOptions {
  query?: never
  path?: never
  body?: never
  signal?: AbortSignal
}

export function getCatalogCategories(
  options: GetCatalogCategoriesOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<CatalogCategoriesResponse> {
  return requestJson<CatalogCategoriesResponse>(
    buildGetCatalogCategoriesPath(),
    {
    ...requestOptions,
    method: 'GET',
    signal: options.signal,
    },
  )
}
export interface GetCatalogItemsOptions {
  query: CatalogItemsQuery
  path?: never
  body?: never
  signal?: AbortSignal
}

export function getCatalogItems(
  options: GetCatalogItemsOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<CatalogItemsResponse> {
  return requestJson<CatalogItemsResponse>(
    buildGetCatalogItemsPath(),
    {
    ...requestOptions,
    method: 'GET',
    searchParams: buildSearchParams(options.query),
    signal: options.signal,
    },
  )
}
export interface GetCatalogItemOptions {
  query?: never
  path: operations['get_item']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function getCatalogItem(
  options: GetCatalogItemOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<CatalogItemResponse> {
  return requestJson<CatalogItemResponse>(
    buildGetCatalogItemPath(options.path),
    {
    ...requestOptions,
    method: 'GET',
    signal: options.signal,
    },
  )
}
export interface GetCatalogStoreOptions {
  query?: never
  path?: never
  body?: never
  signal?: AbortSignal
}

export function getCatalogStore(
  options: GetCatalogStoreOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<CatalogStoreCatalogResponse> {
  return requestJson<CatalogStoreCatalogResponse>(
    buildGetCatalogStorePath(),
    {
    ...requestOptions,
    method: 'GET',
    signal: options.signal,
    },
  )
}

// Examples
export interface PostExamplesEchoOptions {
  query?: never
  path?: never
  body: ExamplePayload
  signal?: AbortSignal
}

export function postExamplesEcho(
  options: PostExamplesEchoOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<ExamplePayloadResponse> {
  return requestJson<ExamplePayloadResponse>(
    buildPostExamplesEchoPath(),
    {
    ...requestOptions,
    method: 'POST',
    json: options.body,
    signal: options.signal,
    },
  )
}
export interface GetExamplesItemOptions {
  query?: never
  path: operations['get_example_item']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function getExamplesItem(
  options: GetExamplesItemOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<ExampleItemResponse> {
  return requestJson<ExampleItemResponse>(
    buildGetExamplesItemPath(options.path),
    {
    ...requestOptions,
    method: 'GET',
    signal: options.signal,
    },
  )
}
export interface GetExamplesSearchOptions {
  query: ExampleSearchQuery
  path?: never
  body?: never
  signal?: AbortSignal
}

export function getExamplesSearch(
  options: GetExamplesSearchOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<ExampleSearchResponse> {
  return requestJson<ExampleSearchResponse>(
    buildGetExamplesSearchPath(),
    {
    ...requestOptions,
    method: 'GET',
    searchParams: buildSearchParams(options.query),
    signal: options.signal,
    },
  )
}

// Identity
export interface PostIdentityUsersOptions {
  query?: never
  path?: never
  body: CreateIdentityUserRequest
  signal?: AbortSignal
}

export function postIdentityUsers(
  options: PostIdentityUsersOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<IdentityUserResponse> {
  return requestJson<IdentityUserResponse>(
    buildPostIdentityUsersPath(),
    {
    ...requestOptions,
    method: 'POST',
    json: options.body,
    signal: options.signal,
    },
  )
}
export interface GetIdentityUserOptions {
  query?: never
  path: operations['get_user']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function getIdentityUser(
  options: GetIdentityUserOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<IdentityUserResponse> {
  return requestJson<IdentityUserResponse>(
    buildGetIdentityUserPath(options.path),
    {
    ...requestOptions,
    method: 'GET',
    signal: options.signal,
    },
  )
}
export interface PostIdentityUserDisableOptions {
  query?: never
  path: operations['disable_user']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function postIdentityUserDisable(
  options: PostIdentityUserDisableOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<IdentityUserResponse> {
  return requestJson<IdentityUserResponse>(
    buildPostIdentityUserDisablePath(options.path),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}
export interface PostIdentityUserIdentitiesOptions {
  query?: never
  path: operations['bind_user_identity']['parameters']['path']
  body: BindIdentityUserIdentityRequest
  signal?: AbortSignal
}

export function postIdentityUserIdentities(
  options: PostIdentityUserIdentitiesOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<IdentityUserResponse> {
  return requestJson<IdentityUserResponse>(
    buildPostIdentityUserIdentitiesPath(options.path),
    {
    ...requestOptions,
    method: 'POST',
    json: options.body,
    signal: options.signal,
    },
  )
}
export interface PatchIdentityUserProfileOptions {
  query?: never
  path: operations['update_user_profile']['parameters']['path']
  body: UpdateIdentityUserProfileRequest
  signal?: AbortSignal
}

export function patchIdentityUserProfile(
  options: PatchIdentityUserProfileOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<IdentityUserResponse> {
  return requestJson<IdentityUserResponse>(
    buildPatchIdentityUserProfilePath(options.path),
    {
    ...requestOptions,
    method: 'PATCH',
    json: options.body,
    signal: options.signal,
    },
  )
}
export interface PostIdentityUserSoftDeleteOptions {
  query?: never
  path: operations['soft_delete_user']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function postIdentityUserSoftDelete(
  options: PostIdentityUserSoftDeleteOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<IdentityUserResponse> {
  return requestJson<IdentityUserResponse>(
    buildPostIdentityUserSoftDeletePath(options.path),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}

// Orders
export interface GetOrdersOptions {
  query?: never
  path?: never
  body?: never
  signal?: AbortSignal
}

export function getOrders(
  options: GetOrdersOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<OrderListResponse> {
  return requestJson<OrderListResponse>(
    buildGetOrdersPath(),
    {
    ...requestOptions,
    method: 'GET',
    signal: options.signal,
    },
  )
}
export interface PostOrdersOptions {
  query?: never
  path?: never
  body: PlaceOrderRequest
  signal?: AbortSignal
}

export function postOrders(
  options: PostOrdersOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<OrderResponse> {
  return requestJson<OrderResponse>(
    buildPostOrdersPath(),
    {
    ...requestOptions,
    method: 'POST',
    json: options.body,
    signal: options.signal,
    },
  )
}
export interface GetOrderOptions {
  query?: never
  path: operations['get_order']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function getOrder(
  options: GetOrderOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<OrderResponse> {
  return requestJson<OrderResponse>(
    buildGetOrderPath(options.path),
    {
    ...requestOptions,
    method: 'GET',
    signal: options.signal,
    },
  )
}
export interface PostOrderAcceptOptions {
  query?: never
  path: operations['accept_order']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function postOrderAccept(
  options: PostOrderAcceptOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<FulfillmentOrderResponse> {
  return requestJson<FulfillmentOrderResponse>(
    buildPostOrderAcceptPath(options.path),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}
export interface PostOrderCancelOptions {
  query?: never
  path: operations['cancel_order']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function postOrderCancel(
  options: PostOrderCancelOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<OrderResponse> {
  return requestJson<OrderResponse>(
    buildPostOrderCancelPath(options.path),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}
export interface PostOrderCompleteOptions {
  query?: never
  path: operations['complete_order']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function postOrderComplete(
  options: PostOrderCompleteOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<FulfillmentOrderResponse> {
  return requestJson<FulfillmentOrderResponse>(
    buildPostOrderCompletePath(options.path),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}
export interface PostOrderReadyOptions {
  query?: never
  path: operations['mark_order_ready']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function postOrderReady(
  options: PostOrderReadyOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<FulfillmentOrderResponse> {
  return requestJson<FulfillmentOrderResponse>(
    buildPostOrderReadyPath(options.path),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}
export interface PostOrderRejectOptions {
  query?: never
  path: operations['reject_order']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function postOrderReject(
  options: PostOrderRejectOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<FulfillmentOrderResponse> {
  return requestJson<FulfillmentOrderResponse>(
    buildPostOrderRejectPath(options.path),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}
export interface PostOrderStartPreparingOptions {
  query?: never
  path: operations['start_preparing_order']['parameters']['path']
  body?: never
  signal?: AbortSignal
}

export function postOrderStartPreparing(
  options: PostOrderStartPreparingOptions,
  requestOptions: RuntimeRequestOptions = {},
): Promise<FulfillmentOrderResponse> {
  return requestJson<FulfillmentOrderResponse>(
    buildPostOrderStartPreparingPath(options.path),
    {
    ...requestOptions,
    method: 'POST',
    signal: options.signal,
    },
  )
}
