// This file is auto-generated by vite-plugin-openapi-codegen.
// Do not edit manually. Changes will be overwritten on next build.

import type { components } from './api-types'

export type AuthMeResponse = components['schemas']['AuthMeResponse']
export type AuthResponse = components['schemas']['AuthResponse']
export type BindIdentityUserIdentityRequest =
  components['schemas']['BindIdentityUserIdentityRequest']
export type CatalogCategoriesResponse = components['schemas']['CatalogCategoriesResponse']
export type CatalogCategoryResponse = components['schemas']['CatalogCategoryResponse']
export type CatalogItemPath = components['schemas']['CatalogItemPath']
export type CatalogItemResponse = components['schemas']['CatalogItemResponse']
export type CatalogItemsQuery = components['schemas']['CatalogItemsQuery']
export type CatalogItemsResponse = components['schemas']['CatalogItemsResponse']
export type CatalogStoreCatalogResponse = components['schemas']['CatalogStoreCatalogResponse']
export type CreateIdentityUserIdentityRequest =
  components['schemas']['CreateIdentityUserIdentityRequest']
export type CreateIdentityUserRequest = components['schemas']['CreateIdentityUserRequest']
export type DependencyChecks = components['schemas']['DependencyChecks']
export type ErrorDetails = components['schemas']['ErrorDetails']
export type ErrorEnvelope = components['schemas']['ErrorEnvelope']
export type ExampleItemPath = components['schemas']['ExampleItemPath']
export type ExampleItemResponse = components['schemas']['ExampleItemResponse']
export type ExamplePayload = components['schemas']['ExamplePayload']
export type ExamplePayloadResponse = components['schemas']['ExamplePayloadResponse']
export type ExampleSearchQuery = components['schemas']['ExampleSearchQuery']
export type ExampleSearchResponse = components['schemas']['ExampleSearchResponse']
export type FieldIssue = components['schemas']['FieldIssue']
export type FieldLocation = components['schemas']['FieldLocation']
export type FulfillmentOrderItemResponse = components['schemas']['FulfillmentOrderItemResponse']
export type FulfillmentOrderPath = components['schemas']['FulfillmentOrderPath']
export type FulfillmentOrderResponse = components['schemas']['FulfillmentOrderResponse']
export type IdentityUserIdentityResponse = components['schemas']['IdentityUserIdentityResponse']
export type IdentityUserPath = components['schemas']['IdentityUserPath']
export type IdentityUserProfileResponse = components['schemas']['IdentityUserProfileResponse']
export type IdentityUserResponse = components['schemas']['IdentityUserResponse']
export type LiveResponse = components['schemas']['LiveResponse']
export type LoginRequest = components['schemas']['LoginRequest']
export type OrderItemResponse = components['schemas']['OrderItemResponse']
export type OrderListItemResponse = components['schemas']['OrderListItemResponse']
export type OrderListResponse = components['schemas']['OrderListResponse']
export type OrderPath = components['schemas']['OrderPath']
export type OrderResponse = components['schemas']['OrderResponse']
export type PageMeta = components['schemas']['PageMeta']
export type PlaceOrderItemRequest = components['schemas']['PlaceOrderItemRequest']
export type PlaceOrderRequest = components['schemas']['PlaceOrderRequest']
export type ReadyResponse = components['schemas']['ReadyResponse']
export type UpdateIdentityUserProfileRequest =
  components['schemas']['UpdateIdentityUserProfileRequest']

// Legacy aliases
export type MenuStoreResponse = CatalogStoreCatalogResponse
export type MenuCategoriesResponse = CatalogCategoriesResponse
export type MenuCategoryResponse = CatalogCategoryResponse
export type MenuItemPath = CatalogItemPath
export type MenuItemResponse = CatalogItemResponse
export type MenuItemsQuery = CatalogItemsQuery
export type MenuItemsResponse = CatalogItemsResponse
