import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { Plugin, ResolvedConfig } from 'vite-plus'

export interface Options {
  /** Path to openapi.json (relative to project root) */
  input: string
  /** Output directory for generated files (relative to project root) */
  output: string
  /** Legacy type aliases for types.ts: { OldName: 'NewName' } */
  legacyAliases?: Record<string, string>
}

const PRINT_WIDTH = 100
const GENERATED_HEADER = [
  '// This file is auto-generated by vite-plugin-openapi-codegen.',
  '// Do not edit manually. Changes will be overwritten on next build.',
]
const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'patch'] as const

type HttpMethod = (typeof HTTP_METHODS)[number]
type ParameterLocation = 'path' | 'query' | 'header' | 'cookie'

interface OpenAPIParameter {
  in: ParameterLocation
  name: string
  required?: boolean
  schema?: {
    type?: string | string[]
  }
}

interface OpenAPIContent {
  schema?: unknown
}

interface OpenAPIRequestBody {
  content?: Record<string, OpenAPIContent>
  required?: boolean
}

interface OpenAPIResponse {
  content?: Record<string, OpenAPIContent>
  description?: string
}

interface OpenAPIOperation {
  operationId?: string
  parameters?: OpenAPIParameter[]
  requestBody?: OpenAPIRequestBody
  responses?: Record<string, OpenAPIResponse>
  tags?: string[]
}

type OpenAPIPathItem = Partial<Record<HttpMethod, OpenAPIOperation>>

interface OpenAPISchema {
  properties?: Record<string, unknown>
  type?: string
}

interface OpenAPISpec {
  paths?: Record<string, OpenAPIPathItem>
  components?: { schemas?: Record<string, OpenAPISchema> }
}

interface OperationEntry {
  apiPath: string
  funcName: string
  group: string
  method: HttpMethod
  operation: OpenAPIOperation
  operationId: string
  strippedPath: string
}

interface GeneratedArtifacts {
  api: string
  client: string
  types: string
}

interface NormalizedChannel {
  present: boolean
  required: boolean
  typeExpr: string | null
}

interface NormalizedOperation {
  builderAlias: string
  entry: OperationEntry
  optionTypeName: string
  pathChannel: NormalizedChannel
  pathInvocationExpr: string
  queryChannel: NormalizedChannel
  requestFunction: 'requestJson' | 'requestVoid'
  responseTypeExpr: string | null
  returnTypeExpr: string
  bodyChannel: NormalizedChannel
}

interface ClientRenderModel {
  operations: NormalizedOperation[]
  needsSearchParamsHelper: boolean
  typeImports: string[]
}

interface NormalizationContext {
  schemaAliasIndex: Map<string, string[]>
  schemaNames: Set<string>
}

interface SuccessResponseInfo {
  hasJsonBody: boolean
  statusKey: string
}

async function generateApiTypes(inputPath: string, outputDir: string): Promise<void> {
  const { default: openapiTS, astToString } = await import('openapi-typescript')
  const ast = await openapiTS(new URL(`file://${inputPath}`))
  const contents = astToString(ast)
  writeFileSync(
    resolve(outputDir, 'api-types.d.ts'),
    `${GENERATED_HEADER.join('\n')}\n\n${contents}`,
  )
}

function renderTypesBarrel(spec: OpenAPISpec, legacyAliases?: Record<string, string>): string {
  const schemaNames = Object.keys(spec.components?.schemas ?? {}).sort()
  if (schemaNames.length === 0) {
    throw new Error('No schemas found in openapi.json')
  }

  const lines: string[] = [
    ...GENERATED_HEADER,
    '',
    "import type { components } from './api-types'",
    '',
  ]

  for (const name of schemaNames) {
    const oneLiner = `export type ${name} = components['schemas']['${name}']`
    if (oneLiner.length > PRINT_WIDTH) {
      lines.push(`export type ${name} =`)
      lines.push(`  components['schemas']['${name}']`)
    } else {
      lines.push(oneLiner)
    }
  }

  if (legacyAliases && Object.keys(legacyAliases).length > 0) {
    lines.push('')
    lines.push('// Legacy aliases')
    for (const [alias, target] of Object.entries(legacyAliases)) {
      lines.push(`export type ${alias} = ${target}`)
    }
  }

  lines.push('')
  return lines.join('\n')
}

function renderApi(spec: OpenAPISpec): string {
  const entries = collectOperations(spec)
  let needsOperationsImport = false

  const groups = new Map<string, string[]>()

  for (const entry of entries) {
    const pathParameters = getEffectiveParametersByLocation(entry, 'path')
    const lines: string[] = []

    if (pathParameters.length === 0) {
      lines.push(`export function ${entry.funcName}(): string {`)
      lines.push(`  return '${entry.strippedPath}'`)
      lines.push('}')
    } else {
      needsOperationsImport = true
      const paramType = `operations['${entry.operationId}']['parameters']['path']`
      const template = entry.strippedPath.replace(
        /\{(\w+)\}/g,
        (_, name: string) => `\${params.${name}}`,
      )
      const signature = `export function ${entry.funcName}(params: ${paramType}): string {`

      if (signature.length > PRINT_WIDTH) {
        lines.push(`export function ${entry.funcName}(`)
        lines.push(`  params: ${paramType},`)
        lines.push('): string {')
      } else {
        lines.push(signature)
      }
      lines.push(`  return \`${template}\``)
      lines.push('}')
    }

    pushGrouped(groups, entry.group, lines.join('\n'))
  }

  const lines: string[] = [...GENERATED_HEADER]
  if (needsOperationsImport) {
    lines.push('')
    lines.push("import type { operations } from './api-types'")
  }

  appendGroupedBlocks(lines, groups)
  lines.push('')
  return lines.join('\n')
}

function renderClient(spec: OpenAPISpec): string {
  const model = buildClientRenderModel(spec)
  if (model.operations.length === 0) {
    throw new Error('No /api/ paths found in openapi.json')
  }

  const lines: string[] = [
    ...GENERATED_HEADER,
    '',
    "import type { ApiRequestOptions } from '#/integrations/http'",
    "import { requestJson, requestVoid } from '#/integrations/http'",
    "import type { operations } from './api-types'",
  ]

  const typeImportLines = renderTypeImports(model.typeImports)
  if (typeImportLines.length > 0) {
    lines.push('')
    lines.push(...typeImportLines)
  }

  lines.push('')
  lines.push(...renderBuilderImports(model.operations))
  lines.push('')
  lines.push(
    "type RuntimeRequestOptions = Omit<ApiRequestOptions, 'json' | 'method' | 'searchParams' | 'signal'>",
  )

  if (model.needsSearchParamsHelper) {
    lines.push('')
    lines.push(
      'function buildSearchParams(query: Record<string, unknown>): URLSearchParams | undefined {',
    )
    lines.push('  const entries = Object.entries(query).filter(([, value]) => value != null)')
    lines.push('  if (entries.length === 0) return undefined')
    lines.push('  const searchParams = new URLSearchParams()')
    lines.push('  for (const [key, value] of entries) {')
    lines.push('    searchParams.set(key, String(value))')
    lines.push('  }')
    lines.push('  return searchParams')
    lines.push('}')
  }

  const groups = new Map<string, string[]>()
  for (const operation of model.operations) {
    const blocks = [renderClientOptions(operation), renderClientFunction(operation)]
    pushGrouped(groups, operation.entry.group, blocks.join('\n\n'))
  }

  appendGroupedBlocks(lines, groups)
  lines.push('')
  return lines.join('\n')
}

function buildClientRenderModel(spec: OpenAPISpec): ClientRenderModel {
  const context = buildNormalizationContext(spec)
  const typeImports = new Set<string>()
  const operations = collectOperations(spec).map((entry) =>
    normalizeOperation(entry, context, typeImports),
  )

  return {
    operations,
    needsSearchParamsHelper: operations.some((operation) => operation.queryChannel.present),
    typeImports: [...typeImports].sort(),
  }
}

function buildNormalizationContext(spec: OpenAPISpec): NormalizationContext {
  const schemaAliasIndex = new Map<string, string[]>()
  const schemaNames = new Set<string>()

  for (const [name, schema] of Object.entries(spec.components?.schemas ?? {})) {
    schemaNames.add(name)

    const props = Object.keys(schema.properties ?? {})
      .sort()
      .join(',')
    if (!props) {
      continue
    }

    if (!schemaAliasIndex.has(props)) {
      schemaAliasIndex.set(props, [])
    }

    schemaAliasIndex.get(props)?.push(name)
  }

  return {
    schemaAliasIndex,
    schemaNames,
  }
}

export function renderGeneratedArtifacts(
  spec: OpenAPISpec,
  options: Pick<Options, 'legacyAliases'>,
): GeneratedArtifacts {
  return {
    api: renderApi(spec),
    client: renderClient(spec),
    types: renderTypesBarrel(spec, options.legacyAliases),
  }
}

function collectOperations(spec: OpenAPISpec): OperationEntry[] {
  const apiPaths = Object.keys(spec.paths ?? {})
    .filter((path) => path.startsWith('/api/'))
    .sort()

  if (apiPaths.length === 0) {
    throw new Error('No /api/ paths found in openapi.json')
  }

  const entries: OperationEntry[] = []

  for (const apiPath of apiPaths) {
    const pathItem = spec.paths?.[apiPath]
    if (!pathItem) continue

    for (const method of HTTP_METHODS) {
      const operation = pathItem[method]
      if (!operation?.operationId) continue

      const strippedPath = apiPath.replace('/api/', '')
      entries.push({
        apiPath,
        funcName: makeFuncName(method, apiPath),
        group: strippedPath.split('/')[0] ?? 'misc',
        method,
        operation,
        operationId: operation.operationId,
        strippedPath,
      })
    }
  }

  return entries
}

function getParametersByLocation(
  operation: OpenAPIOperation,
  location: ParameterLocation,
): OpenAPIParameter[] {
  return (operation.parameters ?? []).filter((parameter) => parameter.in === location)
}

function getEffectiveParametersByLocation(
  entry: OperationEntry,
  location: ParameterLocation,
): OpenAPIParameter[] {
  return (entry.operation.parameters ?? []).filter(
    (parameter) => getEffectiveParameterLocation(entry.apiPath, parameter) === location,
  )
}

function hasRequiredChannel(parameters: OpenAPIParameter[]): boolean {
  return parameters.some((parameter) => parameter.required)
}

function getJsonRequestBody(operation: OpenAPIOperation): OpenAPIContent | undefined {
  const requestBody = operation.requestBody
  if (!requestBody) return undefined

  const jsonBody = requestBody.content?.['application/json']
  if (!jsonBody) {
    throw new Error(
      `Operation "${operation.operationId ?? 'unknown'}" has a requestBody but no application/json content`,
    )
  }

  return jsonBody
}

function getSuccessResponseInfo(operation: OpenAPIOperation): SuccessResponseInfo {
  const successResponses = Object.entries(operation.responses ?? {})
    .filter(([statusKey]) => isSuccessStatus(statusKey))
    .sort(([left], [right]) => Number(left) - Number(right))

  if (successResponses.length === 0) {
    throw new Error(`Operation "${operation.operationId ?? 'unknown'}" has no 2xx success response`)
  }

  const withJson = successResponses.find(([, response]) => response.content?.['application/json'])
  if (withJson) {
    return {
      hasJsonBody: true,
      statusKey: withJson[0],
    }
  }

  return {
    hasJsonBody: false,
    statusKey: successResponses[0][0],
  }
}

function isSuccessStatus(statusKey: string): boolean {
  const value = Number(statusKey)
  return Number.isInteger(value) && value >= 200 && value < 300
}

function renderBuilderImports(operations: NormalizedOperation[]): string[] {
  const importLines = ['import {']

  for (const operation of operations) {
    importLines.push(`  ${operation.entry.funcName} as ${operation.builderAlias},`)
  }

  importLines.push("} from './api'")
  return importLines
}

function renderTypeImports(typeImports: string[]): string[] {
  if (typeImports.length === 0) {
    return []
  }

  const singleLine = `import type { ${typeImports.join(', ')} } from './types'`
  if (singleLine.length <= PRINT_WIDTH) {
    return [singleLine]
  }

  return ['import type {', ...typeImports.map((name) => `  ${name},`), "} from './types'"]
}

function renderClientOptions(operation: NormalizedOperation): string {
  const lines: string[] = [`export interface ${operation.optionTypeName} {`]
  lines.push(renderClientChannelField('query', operation.queryChannel))
  lines.push(renderClientChannelField('path', operation.pathChannel))
  lines.push(renderClientChannelField('body', operation.bodyChannel))
  lines.push('  signal?: AbortSignal')
  lines.push('}')
  return lines.join('\n')
}

function renderClientChannelField(
  key: 'body' | 'path' | 'query',
  channel: NormalizedChannel,
): string {
  if (!channel.present || !channel.typeExpr) {
    return `  ${key}?: never`
  }

  const modifier = channel.required ? '' : '?'
  return `  ${key}${modifier}: ${channel.typeExpr}`
}

function renderClientFunction(operation: NormalizedOperation): string {
  const lines: string[] = [
    `export function ${operation.entry.funcName}(`,
    `  options: ${operation.optionTypeName},`,
    '  requestOptions: RuntimeRequestOptions = {},',
    `): ${operation.returnTypeExpr} {`,
    operation.responseTypeExpr
      ? `  return ${operation.requestFunction}<${operation.responseTypeExpr}>(`
      : `  return ${operation.requestFunction}(`,
    `    ${operation.pathInvocationExpr},`,
    '    {',
    '    ...requestOptions,',
    `    method: '${operation.entry.method.toUpperCase()}',`,
  ]

  if (operation.queryChannel.present) {
    lines.push('    searchParams: buildSearchParams(options.query),')
  }

  if (operation.bodyChannel.present) {
    lines.push('    json: options.body,')
  }

  lines.push('    signal: options.signal,')
  lines.push('    },')
  lines.push('  )')
  lines.push('}')

  return lines.join('\n')
}

function formatStatusKey(statusKey: string): string {
  return Number.isInteger(Number(statusKey)) ? statusKey : `'${statusKey}'`
}

function getBuilderAlias(funcName: string): string {
  return `build${capitalize(funcName)}Path`
}

function getClientOptionTypeName(funcName: string): string {
  return `${capitalize(funcName)}Options`
}

function appendGroupedBlocks(lines: string[], groups: Map<string, string[]>): void {
  for (const [group, blocks] of groups) {
    lines.push('')
    lines.push(`// ${capitalize(group)}`)
    for (const block of blocks) {
      lines.push(block)
    }
  }
}

function pushGrouped(groups: Map<string, string[]>, group: string, block: string): void {
  if (!groups.has(group)) {
    groups.set(group, [])
  }

  groups.get(group)?.push(block)
}

function makeFuncName(method: HttpMethod, apiPath: string): string {
  const segments = apiPath.replace('/api/', '').split('/')
  const result: string[] = []

  for (const segment of segments) {
    if (segment.startsWith('{')) {
      const resource = segment.slice(1, -1).replace(/_id$/, '')
      if (result.length > 0) {
        result[result.length - 1] = resource
      }
      continue
    }

    result.push(segment)
  }

  const camelParts = result.map((segment, index) => {
    const clean = segment.replace(/-([a-z])/g, (_, char: string) => char.toUpperCase())
    return index === 0 ? clean : `${clean[0].toUpperCase()}${clean.slice(1)}`
  })
  const baseName = camelParts.join('')
  return `${method}${capitalize(baseName)}`
}

function capitalize(value: string): string {
  if (value.length === 0) return value
  return `${value[0].toUpperCase()}${value.slice(1)}`
}

function getEffectiveParameterLocation(
  apiPath: string,
  parameter: OpenAPIParameter,
): ParameterLocation {
  if (parameter.in !== 'path') {
    return parameter.in
  }

  return getTemplateParameterNames(apiPath).has(parameter.name) ? 'path' : 'query'
}

function getTemplateParameterNames(apiPath: string): Set<string> {
  const matches = apiPath.match(/\{(\w+)\}/g) ?? []
  return new Set(matches.map((match) => match.slice(1, -1)))
}

function resolveParameterTypeExpression(
  entry: OperationEntry,
  context: NormalizationContext,
  location: 'path' | 'query',
  typeImports: Set<string>,
): string {
  const effectiveParameters = getEffectiveParametersByLocation(entry, location)
  if (effectiveParameters.length === 0) {
    return 'never'
  }

  const rawParameters = getParametersByLocation(entry.operation, location)
  if (hasSameParameterNames(rawParameters, effectiveParameters)) {
    return `operations['${entry.operationId}']['parameters']['${location}']`
  }

  const alias = resolveAlias(
    context,
    effectiveParameters.map((parameter) => parameter.name),
    entry.operation.tags?.[0],
  )
  if (alias) {
    typeImports.add(alias)
    return alias
  }

  return renderInlineParameterObject(effectiveParameters)
}

function normalizeOperation(
  entry: OperationEntry,
  context: NormalizationContext,
  typeImports: Set<string>,
): NormalizedOperation {
  const successResponse = getSuccessResponseInfo(entry.operation)
  const builderAlias = getBuilderAlias(entry.funcName)
  const pathChannel = normalizeParameterChannel(entry, context, 'path', typeImports)
  const queryChannel = normalizeParameterChannel(entry, context, 'query', typeImports)
  const bodyChannel = normalizeBodyChannel(entry, context, typeImports)
  const responseTypeExpr = resolveResponseTypeExpression(
    entry,
    context,
    typeImports,
    successResponse,
  )

  return {
    bodyChannel,
    builderAlias,
    entry,
    optionTypeName: getClientOptionTypeName(entry.funcName),
    pathChannel,
    pathInvocationExpr: pathChannel.present ? `${builderAlias}(options.path)` : `${builderAlias}()`,
    queryChannel,
    requestFunction: responseTypeExpr ? 'requestJson' : 'requestVoid',
    responseTypeExpr,
    returnTypeExpr: responseTypeExpr ? `Promise<${responseTypeExpr}>` : 'Promise<void>',
  }
}

function normalizeParameterChannel(
  entry: OperationEntry,
  context: NormalizationContext,
  location: 'path' | 'query',
  typeImports: Set<string>,
): NormalizedChannel {
  const parameters = getEffectiveParametersByLocation(entry, location)
  if (parameters.length === 0) {
    return {
      present: false,
      required: false,
      typeExpr: null,
    }
  }

  return {
    present: true,
    required: hasRequiredChannel(parameters),
    typeExpr: resolveParameterTypeExpression(entry, context, location, typeImports),
  }
}

function normalizeBodyChannel(
  entry: OperationEntry,
  context: NormalizationContext,
  typeImports: Set<string>,
): NormalizedChannel {
  const typeExpr = resolveRequestBodyTypeExpression(entry, context, typeImports)
  if (!typeExpr) {
    return {
      present: false,
      required: false,
      typeExpr: null,
    }
  }

  return {
    present: true,
    required: entry.operation.requestBody?.required !== false,
    typeExpr,
  }
}

function resolveRequestBodyTypeExpression(
  entry: OperationEntry,
  context: NormalizationContext,
  typeImports: Set<string>,
): string | null {
  const jsonBody = getJsonRequestBody(entry.operation)
  if (!jsonBody) {
    return null
  }

  const alias = resolveSchemaAlias(context, jsonBody.schema, typeImports)
  if (alias) {
    return alias
  }

  return `operations['${entry.operationId}']['requestBody']['content']['application/json']`
}

function resolveResponseTypeExpression(
  entry: OperationEntry,
  context: NormalizationContext,
  typeImports: Set<string>,
  successResponse: SuccessResponseInfo,
): string | null {
  if (!successResponse.hasJsonBody) {
    return null
  }

  const response = entry.operation.responses?.[successResponse.statusKey]
  const jsonContent = response?.content?.['application/json']
  const alias = resolveSchemaAlias(context, jsonContent?.schema, typeImports)
  if (alias) {
    return alias
  }

  return `operations['${entry.operationId}']['responses'][${formatStatusKey(
    successResponse.statusKey,
  )}]['content']['application/json']`
}

function hasSameParameterNames(left: OpenAPIParameter[], right: OpenAPIParameter[]): boolean {
  if (left.length !== right.length) {
    return false
  }

  const leftNames = left.map((parameter) => parameter.name).sort()
  const rightNames = right.map((parameter) => parameter.name).sort()
  return leftNames.every((name, index) => name === rightNames[index])
}

function resolveAlias(
  context: NormalizationContext,
  parameterNames: string[],
  tag?: string,
): string | undefined {
  const key = [...parameterNames].sort().join(',')
  const candidates = context.schemaAliasIndex.get(key)
  if (!candidates || candidates.length === 0) {
    return undefined
  }

  if (candidates.length === 1) {
    return candidates[0]
  }

  if (tag) {
    const singularTag = tag.replace(/s$/, '')
    const prefix = `${singularTag[0]?.toUpperCase() ?? ''}${singularTag.slice(1)}`
    const match = candidates.find((candidate) => candidate.startsWith(prefix))
    if (match) {
      return match
    }
  }

  return candidates[0]
}

function resolveSchemaAlias(
  context: NormalizationContext,
  schema: unknown,
  typeImports: Set<string>,
): string | undefined {
  const ref = readSchemaRef(schema)
  if (!ref) {
    return undefined
  }

  const schemaName = ref.split('/').pop()
  if (!schemaName || !context.schemaNames.has(schemaName)) {
    return undefined
  }

  typeImports.add(schemaName)
  return schemaName
}

function readSchemaRef(schema: unknown): string | undefined {
  if (!schema || typeof schema !== 'object') {
    return undefined
  }

  const maybeRef = (schema as { $ref?: unknown }).$ref
  return typeof maybeRef === 'string' ? maybeRef : undefined
}

function renderInlineParameterObject(parameters: OpenAPIParameter[]): string {
  const properties = parameters.map((parameter) => {
    const optionalMarker = parameter.required ? '' : '?'
    return `${parameter.name}${optionalMarker}: ${renderPrimitiveSchemaType(parameter.schema)}`
  })

  return `{ ${properties.join('; ')} }`
}

function renderPrimitiveSchemaType(schema: OpenAPIParameter['schema']): string {
  const type = schema?.type
  if (!type) {
    return 'unknown'
  }

  if (Array.isArray(type)) {
    return type.map((memberType) => mapPrimitiveType(memberType)).join(' | ')
  }

  return mapPrimitiveType(type)
}

function mapPrimitiveType(type: string): string {
  switch (type) {
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'null':
      return 'null'
    case 'string':
      return 'string'
    default:
      return 'unknown'
  }
}

function warnOnParameterLocationMismatch(spec: OpenAPISpec): void {
  for (const entry of collectOperations(spec)) {
    for (const parameter of entry.operation.parameters ?? []) {
      const effectiveLocation = getEffectiveParameterLocation(entry.apiPath, parameter)
      if (effectiveLocation === parameter.in) {
        continue
      }

      console.warn(
        `[openapi-codegen] normalized parameter "${parameter.name}" for "${entry.operationId}" from ${parameter.in} to ${effectiveLocation}.`,
      )
    }
  }
}

async function generate(root: string, options: Options): Promise<void> {
  const inputPath = resolve(root, options.input)
  const outputDir = resolve(root, options.output)
  const spec = JSON.parse(readFileSync(inputPath, 'utf-8')) as OpenAPISpec
  const artifacts = renderGeneratedArtifacts(spec, options)

  warnOnParameterLocationMismatch(spec)
  await generateApiTypes(inputPath, outputDir)
  writeFileSync(resolve(outputDir, 'types.ts'), artifacts.types)
  writeFileSync(resolve(outputDir, 'api.ts'), artifacts.api)
  writeFileSync(resolve(outputDir, 'client.ts'), artifacts.client)
}

export function openapiCodegen(options: Options): Plugin {
  let root = process.cwd()

  return {
    name: 'openapi-codegen',
    enforce: 'pre',

    configResolved(config: ResolvedConfig) {
      root = config.root
    },

    async buildStart() {
      await generate(root, options)
    },

    configureServer(server) {
      const inputPath = resolve(root, options.input)

      server.watcher.add(inputPath)
      server.watcher.on('change', async (path) => {
        if (path === inputPath) {
          console.log('[openapi-codegen] openapi.json changed, regenerating...')
          await generate(root, options)
          console.log('[openapi-codegen] regeneration complete.')
        }
      })
    },
  }
}
