import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { Plugin, ResolvedConfig } from 'vite-plus'

export interface Options {
  /** Path to openapi.json (relative to project root) */
  input: string
  /** Output directory for generated files (relative to project root) */
  output: string
  /** Legacy type aliases for types.ts: { OldName: 'NewName' } */
  legacyAliases?: Record<string, string>
}

const PRINT_WIDTH = 100

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

interface OpenAPISpec {
  paths?: Record<string, unknown>
  components?: { schemas?: Record<string, unknown> }
}

/** Generate api-types.d.ts via openapi-typescript programmatic API */
async function generateApiTypes(inputPath: string, outputDir: string): Promise<void> {
  const { default: openapiTS, astToString } = await import('openapi-typescript')
  const ast = await openapiTS(new URL(`file://${inputPath}`))
  const contents = astToString(ast)
  const header = [
    '// This file is auto-generated by vite-plugin-openapi-codegen.',
    '// Do not edit manually. Changes will be overwritten on next build.',
  ].join('\n')
  writeFileSync(resolve(outputDir, 'api-types.d.ts'), `${header}\n\n${contents}`)
}

/** Generate types.ts barrel that re-exports all schema types */
function generateTypesBarrel(
  spec: OpenAPISpec,
  outputDir: string,
  legacyAliases?: Record<string, string>,
): void {
  const schemaNames = Object.keys(spec.components?.schemas ?? {}).sort()
  if (schemaNames.length === 0) {
    throw new Error('No schemas found in openapi.json')
  }

  const lines: string[] = [
    '// This file is auto-generated by vite-plugin-openapi-codegen.',
    '// Do not edit manually. Changes will be overwritten on next build.',
    '',
    "import type { components } from './api-types'",
    '',
  ]

  for (const name of schemaNames) {
    const oneLiner = `export type ${name} = components['schemas']['${name}']`
    if (oneLiner.length > PRINT_WIDTH) {
      lines.push(`export type ${name} =`)
      lines.push(`  components['schemas']['${name}']`)
    } else {
      lines.push(oneLiner)
    }
  }

  if (legacyAliases && Object.keys(legacyAliases).length > 0) {
    lines.push('')
    lines.push('// Legacy aliases')
    for (const [alias, target] of Object.entries(legacyAliases)) {
      lines.push(`export type ${alias} = ${target}`)
    }
  }

  lines.push('')
  writeFileSync(resolve(outputDir, 'types.ts'), lines.join('\n'))
}

/** Generate api.ts with typed URL builder functions for each API operation */
function generateApi(spec: OpenAPISpec, outputDir: string): void {
  const allPaths = Object.keys(spec.paths ?? {}).sort()
  const apiPaths = allPaths.filter((p) => p.startsWith('/api/'))

  if (apiPaths.length === 0) {
    throw new Error('No /api/ paths found in openapi.json')
  }

  const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'patch'] as const

  interface FuncEntry {
    group: string
    name: string
    code: string
  }

  let needsBuildQuery = false
  let needsOperationsImport = false
  const typesImports = new Set<string>()

  // Build schema property lookup: "prop1,prop2" → [SchemaName, ...]
  const schemas = spec.components?.schemas ?? {}
  const schemasByProps = new Map<string, string[]>()
  for (const [name, schema] of Object.entries(schemas)) {
    const props = Object.keys(((schema as Record<string, unknown>).properties as object) ?? {})
      .sort()
      .join(',')
    if (props) {
      if (!schemasByProps.has(props)) schemasByProps.set(props, [])
      schemasByProps.get(props)!.push(name)
    }
  }

  /** Resolve a schema alias from types.ts that matches the operation's params */
  function resolveAlias(paramNames: string[], tag?: string): string | undefined {
    const key = [...paramNames].sort().join(',')
    const candidates = schemasByProps.get(key)
    if (!candidates || candidates.length === 0) return undefined
    if (candidates.length === 1) return candidates[0]

    // Disambiguate by tag prefix: "orders" → "Order", "catalog" → "Catalog"
    if (tag) {
      const prefix = tag.replace(/s$/, '')[0].toUpperCase() + tag.replace(/s$/, '').slice(1)
      const match = candidates.find((n) => n.startsWith(prefix))
      if (match) return match
    }
    return candidates[0]
  }

  /** Extract param names that appear as {param} in the URL template */
  function getUrlParamNames(urlTemplate: string): Set<string> {
    const matches = urlTemplate.match(/\{(\w+)\}/g) || []
    return new Set(matches.map((m) => m.slice(1, -1)))
  }

  /** Build function name: method prefix + camelCase path segments */
  function makeFuncName(method: string, apiPath: string): string {
    const segments = apiPath.replace('/api/', '').split('/')
    const result: string[] = []

    for (let i = 0; i < segments.length; i++) {
      const seg = segments[i]
      if (seg.startsWith('{')) {
        // Replace preceding segment with singular form from param name
        const resource = seg.slice(1, -1).replace(/_id$/, '')
        if (result.length > 0) {
          result[result.length - 1] = resource
        }
      } else {
        result.push(seg)
      }
    }

    const camelParts = result.map((s, i) => {
      const clean = s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
      return i === 0 ? clean : clean[0].toUpperCase() + clean.slice(1)
    })
    const baseName = camelParts.join('')
    return method + baseName[0].toUpperCase() + baseName.slice(1)
  }

  function makeEntry(
    method: string,
    apiPath: string,
    operationId: string,
    tag?: string,
  ): FuncEntry {
    const segments = apiPath.replace('/api/', '').split('/')
    const group = segments[0]
    const funcName = makeFuncName(method, apiPath)
    const strippedPath = apiPath.replace('/api/', '')

    // Check if operation has parameters
    const operation = (spec.paths![apiPath] as Record<string, unknown>)[method] as {
      parameters?: Array<{ name: string }>
    }
    const params = operation?.parameters ?? []

    if (params.length === 0) {
      // No params — simple function returning constant path
      const code = [
        `export function ${funcName}(): string {`,
        `  return '${strippedPath}'`,
        '}',
      ].join('\n')
      return { group, name: funcName, code }
    }

    // Try to resolve a schema alias from types.ts
    const paramNames = params.map((p) => p.name)
    const alias = resolveAlias(paramNames, tag)

    let paramType: string
    if (alias) {
      typesImports.add(alias)
      paramType = alias
    } else {
      needsOperationsImport = true
      paramType = `operations['${operationId}']['parameters']['path']`
    }

    // Determine which params are path (in URL template) vs query (not in template)
    const urlParamNames = getUrlParamNames(apiPath)
    const queryParamNames = paramNames.filter((n) => !urlParamNames.has(n))
    const hasPathParams = urlParamNames.size > 0
    const hasQueryParams = queryParamNames.length > 0

    if (hasQueryParams) needsBuildQuery = true

    let returnExpr: string

    if (hasPathParams && !hasQueryParams) {
      // Only path params — template literal
      const template = strippedPath.replace(/\{(\w+)\}/g, (_, name: string) => `\${params.${name}}`)
      returnExpr = '`' + template + '`'
    } else if (!hasPathParams && hasQueryParams) {
      // Only query params — constant path + buildQuery
      returnExpr = `'${strippedPath}' + buildQuery(params)`
    } else {
      // Mixed path + query — destructure path params, rest as query
      const pathParamList = [...urlParamNames].join(', ')
      const template = strippedPath.replace(/\{(\w+)\}/g, (_, name: string) => `\${${name}}`)
      const lines: string[] = []
      lines.push(`export function ${funcName}(params: ${paramType}): string {`)
      lines.push(`  const { ${pathParamList}, ...query } = params`)
      lines.push('  return `' + template + '` + buildQuery(query)')
      lines.push('}')
      return { group, name: funcName, code: lines.join('\n') }
    }

    // Standard function generation with print-width awareness
    const sigLine = `export function ${funcName}(params: ${paramType}): string {`
    const retLine = `  return ${returnExpr}`

    const lines: string[] = []
    if (sigLine.length > PRINT_WIDTH) {
      lines.push(`export function ${funcName}(`)
      lines.push(`  params: ${paramType},`)
      lines.push('): string {')
    } else {
      lines.push(sigLine)
    }
    lines.push(retLine)
    lines.push('}')
    return { group, name: funcName, code: lines.join('\n') }
  }

  const entries: FuncEntry[] = []

  for (const apiPath of apiPaths) {
    const pathItem = spec.paths![apiPath] as Record<string, unknown>
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method] as
        | {
            operationId?: string
            tags?: string[]
          }
        | undefined
      if (!operation?.operationId) continue
      entries.push(makeEntry(method, apiPath, operation.operationId, operation.tags?.[0]))
    }
  }

  // Group by domain (first path segment)
  const groups = new Map<string, FuncEntry[]>()
  for (const entry of entries) {
    if (!groups.has(entry.group)) groups.set(entry.group, [])
    groups.get(entry.group)!.push(entry)
  }

  const lines: string[] = [
    '// This file is auto-generated by vite-plugin-openapi-codegen.',
    '// Do not edit manually. Changes will be overwritten on next build.',
  ]

  const imports: string[] = []
  if (typesImports.size > 0) {
    const sorted = [...typesImports].sort()
    const importLine = `import type { ${sorted.join(', ')} } from './types'`
    if (importLine.length > PRINT_WIDTH) {
      imports.push('import type {')
      for (const name of sorted) {
        imports.push(`  ${name},`)
      }
      imports.push("} from './types'")
    } else {
      imports.push(importLine)
    }
  }
  if (needsOperationsImport) {
    imports.push("import type { operations } from './api-types'")
  }
  if (imports.length > 0) {
    lines.push('')
    lines.push(...imports)
  }

  if (needsBuildQuery) {
    lines.push('')
    lines.push('function buildQuery(params: Record<string, unknown>): string {')
    lines.push('  const entries = Object.entries(params).filter(([, v]) => v != null)')
    lines.push("  if (entries.length === 0) return ''")
    lines.push(
      "  return '?' + entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')",
    )
    lines.push('}')
  }

  for (const [group, items] of groups) {
    lines.push('')
    lines.push(`// ${group[0].toUpperCase() + group.slice(1)}`)
    for (const item of items) {
      lines.push(item.code)
    }
  }

  lines.push('')
  writeFileSync(resolve(outputDir, 'api.ts'), lines.join('\n'))
}

// ---------------------------------------------------------------------------
// Core generate function
// ---------------------------------------------------------------------------

async function generate(root: string, options: Options): Promise<void> {
  const inputPath = resolve(root, options.input)
  const outputDir = resolve(root, options.output)

  const spec: OpenAPISpec = JSON.parse(readFileSync(inputPath, 'utf-8'))

  await generateApiTypes(inputPath, outputDir)
  generateTypesBarrel(spec, outputDir, options.legacyAliases)
  generateApi(spec, outputDir)
}

// ---------------------------------------------------------------------------
// Vite plugin
// ---------------------------------------------------------------------------

export function openapiCodegen(options: Options): Plugin {
  let root: string

  return {
    name: 'openapi-codegen',
    enforce: 'pre',

    configResolved(config: ResolvedConfig) {
      root = config.root
    },

    async configureServer(server) {
      const inputPath = resolve(root, options.input)

      // Generate on dev server start
      await generate(root, options)

      // Watch openapi.json for changes and regenerate
      server.watcher.add(inputPath)
      server.watcher.on('change', async (path) => {
        if (path === inputPath) {
          console.log('[openapi-codegen] openapi.json changed, regenerating...')
          await generate(root, options)
          console.log('[openapi-codegen] regeneration complete.')
        }
      })
    },
  }
}
